"""Deterministic non-authoritative views of the authored OoC graph."""
from __future__ import annotations
import html
from collections import Counter
from pathlib import Path
from .core import canonical, loads, read_graph, resolve, sha256, file_inventory, file_class, subject_digest

PRODUCTS = [
 'generated/graph.json','generated/ooc-graph.jsonld','generated/current_state.json',
 'generated/CURRENT_STATE.md','generated/research_gaps.md','generated/workstreams.md',
 'generated/theory_comparison.md','generated/adapter_matrix.md','generated/source_coverage.md',
 'generated/blockers.md','generated/blockers.json','generated/authority_map.json',
 'generated/evidence_map.json','generated/impact_graph.json','generated/repository_coverage.json',
 'generated/documentation_coverage.json','generated/unresolved_graph_items.json',
 'generated/negative_results.json','generated/data_use_firewall.json','generated/route_atlas.json',
 'generated/model_applicability.json','generated/explorer.html','generated/README.md','manifest.json']

def dump(x): return canonical(x)+'\n'

def _cell(s): return str(s).replace('|','\\|').replace('\n',' ')

def table(headers, rows):
    return '| '+' | '.join(headers)+' |\n| '+' | '.join('---' for _ in headers)+' |\n'+''.join('| '+' | '.join(_cell(x) for x in row)+' |\n' for row in rows)

def make_views(root: Path) -> dict[str, str]:
    records = read_graph(root)
    nodes=[r for r in records if r['type']!='Relation'];edges=[r for r in records if r['type']=='Relation']
    def items(typ):return [r for r in nodes if r['type']==typ]
    counts=Counter(r['type'] for r in nodes)
    project=loads((root/'config/project.json').read_text())
    files=sorted(set(file_inventory(root))|set(PRODUCTS))
    # Full file inventory is a projection. Generated bytes are excluded from its subject.
    coverage=[]
    for p in files:
        kind,zone=file_class(p)
        generated=kind in {'GENERATED_VIEW','RELEASE_DESCRIPTOR'}
        coverage.append({'id':'ooc:repo-file:'+p,'path':p,'file_class':kind,'trust_zone':zone,
                         'sha256':None if generated else sha256((root/p).read_bytes()),'hash_excluded':generated})
    digest=subject_digest(root,files)
    graph_hash=sha256(canonical(records).encode())
    resolver=resolve(records)
    critical=[r for r in items('ResearchGap') if r['priority']=='CRITICAL']
    opencrit=[r for r in critical if r['status'] not in {'RESOLVED','BOUNDED','SUPERSEDED'}]
    required=loads((root/'config/documentation_contract.json').read_text())['required_documents']
    state={'stage':project['scientific_stage'],'kernel_frozen':project['kernel_frozen'],
           'clinical_use_authorized':False,'source_rows':counts['LiteratureSource'],
           'source_identifier_groups':len({r['identifiers_raw'].split('; PMID')[0].strip().lower() for r in items('LiteratureSource')}),
           'bibliographic_verifications':counts['SourceVerification'],
           'completed_paper_extractions':sum(r['extraction_status']=='EXTRACTED' for r in items('LiteratureSource')),
           'theory_cards':counts['Theory'],'completed_theory_cards':sum(r['card_complete'] for r in items('Theory')),
           'workstreams':counts['Workstream'],'research_gaps':counts['ResearchGap'],
           'critical_gaps':len(critical),'open_critical_gaps':len(opencrit),
           'adapters':counts['Adapter'],'completed_adapter_dossiers':sum(r['dossier_complete'] for r in items('Adapter')),
           'model_instances':counts['ModelInstance'],'evidence_objects':counts['EvidenceObject'],
           'evidence_assessments':counts['EvidenceAssessment'],'cancer_empirical_runs':sum(r.get('evidence_class','').startswith('PRIMARY_') for r in items('Result')),
           'record_counts':dict(sorted(counts.items())),'relations':len(edges),
           'graph_sha256':graph_hash,'subject_sha256':digest,'resolver':resolver,
           'interpretation':'Engineering/documentation completeness does not establish scientific completeness.'}
    out={}
    out['generated/graph.json']=dump({'schema_version':'0.1.0','authority':'DERIVED_ONLY','nodes':nodes,'relations':edges,'graph_sha256':graph_hash})
    # Exact property-preserving JSON-LD representation; arrays are encoded as @json payloads.
    out['generated/ooc-graph.jsonld']=dump({'@context':{'ooc':'urn:ooc:','record':{'@id':'urn:ooc:record','@type':'@json'}},'@graph':[{'@id':r['id'],'@type':'urn:ooc:type:'+r['type'],'record':r} for r in records]})
    out['generated/current_state.json']=dump(state)
    out['manifest.json']=dump({'project':project['project'],'version':project['bootstrap_version'],
      'baseline_date':project['baseline_date'],'authority':'GENERATED_NON_SCIENTIFIC',
      'source_base_commit':project['source_repository_base_commit'],'subject_sha256':digest,
      'graph_sha256':graph_hash,'nodes':len(nodes),'relations':len(edges),
      'generated_products':PRODUCTS,'kernel_frozen':project['kernel_frozen'],'clinical_use_authorized':False,
      'commit_identity':'Bound by repository checkout/PR/tag, never embedded into its own source hash.'})
    out['generated/CURRENT_STATE.md']='# Current recorded state\n\n> Generated; no independent scientific authority.\n\n'+table(['Field','State'],[(k,state[k]) for k in ['stage','kernel_frozen','source_rows','source_identifier_groups','bibliographic_verifications','completed_paper_extractions','theory_cards','completed_theory_cards','workstreams','research_gaps','critical_gaps','open_critical_gaps','adapters','completed_adapter_dossiers','model_instances','evidence_objects','evidence_assessments','cancer_empirical_runs']])+'\n**GO research; NO-GO cancer kernel freeze.**\n\nAll missing scientific evidence remains OPEN or UNKNOWN. Source presence, a documentation card, and a passing engineering test are not empirical validation.\n'
    out['generated/research_gaps.md']='# Research gaps\n\n'+table(['ID','Question','Priority','Status','Dossier'],[(r['legacy_id'],r['question'],r['priority'],r['status'],f"[read](../{r['doc_path']})") for r in items('ResearchGap')])
    out['generated/workstreams.md']='# Research workstreams\n\n'+table(['ID','Layer','Workstream','Status','Dossier'],[(r['legacy_id'],r['layer'],r['label'],r['status'],f"[read](../{r['doc_path']})") for r in items('Workstream')])
    out['generated/theory_comparison.md']='# Theory-family intake and comparison\n\nThese are registered OPEN research cards, not completed literature reviews.\n\n'+table(['ID','Family','Status','Card complete','Decision','Card'],[(r['legacy_id'],r['label'],r['status'],r['card_complete'],r['adoption_decision'],f"[read](../{r['doc_path']})") for r in items('Theory')])
    out['generated/adapter_matrix.md']='# Adapter matrix\n\n'+table(['Adapter','Status','Dossier complete','Read'],[(r['label'],r['status'],r['dossier_complete'],f"[dossier](../{r['doc_path']})") for r in items('Adapter')])
    out['generated/source_coverage.md']='# Source coverage\n\nBibliographic registration is separate from metadata verification, extraction, appraisal and independent study evidence.\n\n'+table(['ID','Registered citation','Verification','Extraction','Duplicate identifier','Intake'],[(r['legacy_id'],r['label'],r['bibliographic_verification'],r['extraction_status'],r.get('same_identifier_as',''),f"[read](../{r['doc_path']})") for r in items('LiteratureSource')])
    out['generated/blockers.md']='# Critical kernel-freeze blockers\n\n'+table(['ID','Question','Status'],[(r['legacy_id'],r['question'],r['status']) for r in opencrit])
    out['generated/blockers.json']=dump({'critical_open':[r['id'] for r in opencrit],'requirements':items('Requirement'),'kernel_freeze_allowed':project['kernel_frozen'] and not opencrit})
    out['generated/authority_map.json']=dump({'authorities':items('Authority'),'resolution':resolver,'empirical_truth_ownership':False})
    out['generated/evidence_map.json']=dump({'evidence':items('EvidenceObject'),'assessments':items('EvidenceAssessment'),'sources_are_not_evidence':True})
    out['generated/impact_graph.json']=dump({'scope':'EXPLICIT_DEPENDENCY_EDGES_ONLY','relations':[r for r in edges if r['kind'] in {'BLOCKS','REQUIRES','PART_OF'}],'causal_path_claim':False})
    out['generated/repository_coverage.json']=dump({'files':coverage,'file_count':len(files),'unindexed':[],'unclassified':[],'subject_sha256':digest})
    out['generated/documentation_coverage.json']=dump({'required_documents':required,'missing':[p for p in required if not (root/p).is_file()],'document_presence_is_science_complete':False})
    out['generated/unresolved_graph_items.json']=dump({'research_gaps':[r['id'] for r in items('ResearchGap') if r['status']=='OPEN'],
        'papers_not_extracted':[r['id'] for r in items('LiteratureSource') if r['extraction_status']!='EXTRACTED'],
        'theory_cards_open':[r['id'] for r in items('Theory') if not r['card_complete']],
        'adapters_open':[r['id'] for r in items('Adapter') if not r['dossier_complete']],
        'import_reviews_required':[r['id'] for r in items('MethodImport')],
        'backend_rule':'Empty model-instance and evidence collections are legitimate scientific OPEN, not broken engineering.'})
    out['generated/negative_results.json']=dump({'results':[r for r in items('Result') if r.get('negative_result')], 'absence_is_not_no_failures_in_nature':True})
    out['generated/data_use_firewall.json']=dump({'data_uses':items('DataUse'),'datasets':items('Dataset'),'independence_assumed':False})
    out['generated/route_atlas.json']=dump({'routes':items('Route'),'transitions':items('Transition'),'mvcl_reference_edges':items('MVCLReference'),'reference_edges_are_admitted_routes':False})
    out['generated/model_applicability.json']=dump({'estimands':items('Estimand'),'classes':items('ModelClass'),'instances':items('ModelInstance'),'applicability':items('MethodApplicability'),'universal_backend_selected':False})
    out['generated/README.md']='# Generated views\n\nDo not edit these files. Run `python tools/build.py --write` after an authored change. The graph, resolver, tables and static explorer are projections; they do not create scientific authority. Full graph exports are deterministic and carry no build-time clock.\n'
    payload=canonical({'nodes':nodes,'relations':edges}).replace('<','\\u003c').replace('&','\\u0026')
    out['generated/explorer.html']=EXPLORER.replace('PAYLOAD_JSON',payload)
    assert set(out)==set(PRODUCTS)
    return out

EXPLORER='''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Origin of Cancer — research graph</title>
<style>body{font:16px/1.5 system-ui;margin:0;background:#f5f7fa;color:#152333}header{padding:24px;background:#152333;color:white}main{display:grid;grid-template-columns:minmax(260px,38%) 1fr;gap:20px;padding:20px}input,select,button{font:inherit;padding:8px;border:1px solid #c1ccd8;border-radius:4px}input{width:55%}article,aside{background:white;border:1px solid #d8e0ea;border-radius:6px;padding:16px}.card{padding:10px;margin:8px 0;border:1px solid #c1ccd8;cursor:pointer}.card:hover{background:#edf3f8}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}svg{width:100%;height:250px;background:#f7f9fb}svg text{font:10px system-ui}a{color:#175792}small{display:block} @media(max-width:850px){main{display:block}aside{margin-bottom:16px}}</style>
<header><h1>Origin of Cancer · research graph</h1><p>PRE-FORMALIZATION · no admitted cancer model or biological validation. This view is generated, not an authority.</p><input id="query" placeholder="Search ID, theory, source, gap…"><select id="types"><option value="">All object types</option></select><small id="count"></small></header>
<main><aside><div id="list"></div></aside><article><h2 id="title">Select a research object</h2><p id="notice">Browse the graph, inspect typed relations and open the complete local documentation. No external service or network request is needed.</p><svg id="picture" role="img" aria-label="Selected object's immediate graph neighborhood"></svg><div id="links"></div><h3>Exact record</h3><pre id="detail"></pre><h3>Incoming and outgoing relations</h3><div id="edges"></div></article></main>
<script type="application/json" id="data">PAYLOAD_JSON</script>
<script>
'use strict';const data=JSON.parse(document.getElementById('data').textContent),byId=new Map(data.nodes.map(n=>[n.id,n])),list=document.getElementById('list'),types=document.getElementById('types');
[...new Set(data.nodes.map(n=>n.type))].sort().forEach(t=>{let o=document.createElement('option');o.value=t;o.textContent=t;types.append(o)});
function select(id){const n=byId.get(id);if(!n)return;document.getElementById('title').textContent=n.label;document.getElementById('notice').textContent=n.type+' · '+n.status+' · '+n.id;document.getElementById('detail').textContent=JSON.stringify(n,null,2);const links=document.getElementById('links');links.replaceChildren();for(const p of [n.doc_path,n.path].filter(Boolean)){const a=document.createElement('a');a.href='../'+p;a.textContent='Open '+p;links.append(a,document.createElement('br'))}const es=data.relations.filter(e=>e.source===id||e.target===id);const div=document.getElementById('edges');div.replaceChildren();for(const e of es){const b=document.createElement('button');const other=e.source===id?e.target:e.source;b.textContent=(e.source===id?'→ ':'← ')+e.kind+' · '+(byId.get(other)?.label||other);b.onclick=()=>select(other);div.append(b,document.createElement('br'))}draw(id,es);}
function draw(id,es){const svg=document.getElementById('picture');svg.replaceChildren();svg.setAttribute('viewBox','0 0 600 250');const ns='http://www.w3.org/2000/svg';function el(t,a){const e=document.createElementNS(ns,t);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));return e}const nearby=[...new Set(es.map(e=>e.source===id?e.target:e.source))].slice(0,12);nearby.forEach((nid,i)=>{const angle=2*Math.PI*i/Math.max(nearby.length,1),x=300+200*Math.cos(angle),y=125+90*Math.sin(angle);svg.append(el('line',{x1:300,y1:125,x2:x,y2:y,stroke:'#9babbb'}));const c=el('circle',{cx:x,cy:y,r:9,fill:'#327094'});c.onclick=()=>select(nid);svg.append(c);const text=el('text',{x:x+12,y:y+4});text.textContent=nid.split(':').slice(-1)[0].slice(0,24);svg.append(text)});svg.append(el('circle',{cx:300,cy:125,r:15,fill:'#152333'}));const label=el('text',{x:300,y:155,'text-anchor':'middle'});label.textContent=id.split(':').slice(-1)[0];svg.append(label);}
function render(){const q=document.getElementById('query').value.toLowerCase();const hits=data.nodes.filter(n=>(!types.value||n.type===types.value)&&JSON.stringify(n).toLowerCase().includes(q));document.getElementById('count').textContent=hits.length+' matching objects / '+data.nodes.length+' total; showing first 150';list.replaceChildren();for(const n of hits.slice(0,150)){const d=document.createElement('div');d.className='card';d.tabIndex=0;const h=document.createElement('strong');h.textContent=n.label;const s=document.createElement('small');s.textContent=n.type+' · '+n.status;d.append(h,s);d.onclick=()=>select(n.id);d.onkeydown=e=>{if(e.key==='Enter')select(n.id)};list.append(d)}}document.getElementById('query').oninput=render;types.onchange=render;render();
</script></html>
'''
